spring:
  application:
    name: ${SPRING_APP_NAME}
  profiles:
    active: vault

  cloud:
    config:
      server:
        vault:
          host: ${VAULT_HOST}
          kv-version: ${VAULT_KV_VERSION}
          backend: ${VAULT_BACKEND}
          profile-separator: ${VAULT_PROFILE_SEPARATOR}
          token: ${VAULT_TOKEN}
          port: ${VAULT_PORT:443}
          scheme: ${VAULT_SCHEME:https}

server:
  port: ${SERVER_PORT:8080}
