# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)


name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Repository
      run: |
        DOCKER_URL=https://hub.docker.com/repository/docker/mainforce/spring-cloud-config-server/
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${DOCKER_URL} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=mainforce/spring-cloud-config-server
        IMAGE_TAG=$(date +%s)
        ARCH=amd64
        
        ddocker build --build-arg TARGETARCH=$ARCH --tag $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:$IMAGE_TAG
        
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
        docker push $IMAGE_NAME:latest
